@echo off
echo Python Yukleniyor...
curl -o python-3.11.2.exe https://www.python.org/ftp/python/3.11.2/python-3.11.2-amd64.exe
echo Python Kuruluyor...
start /wait python-3.11.2.exe /quiet InstallAllUsers=1 PrependPath=1
echo Python Kuruldu Herhangi Bir Tusa Basin... 
pause
